name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - development

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: self-hosted
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.HOSTNAME }}
          remote-user: ${{ secrets.USER_NAME }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ${{ secrets.TARGET_DIR }}
